// File generated by FlutterFire CLI or placeholder for manual setup.
// Run `dart run flutterfire_cli:flutterfire configure` to generate your project's options,
// or replace the values below with your Firebase project config from the Firebase console.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return FirebaseOptions(
      apiKey: 'YOUR_WEB_API_KEY',
      appId: '1:000000000000:web:0000000000000000000000',
      messagingSenderId: '000000000000',
      projectId: 'your-project-id',
      authDomain: 'your-project-id.firebaseapp.com',
      storageBucket: 'your-project-id.appspot.com',
    );
  }
}
